# backend/queue.py
#
# ══════════════════════════════════════════════════════════════════════
# ASYNC JOB QUEUE  (S1.1 + S1.2)
# ══════════════════════════════════════════════════════════════════════
#
# Why this file exists
# --------------------
# Without serialised execution, two simultaneous upload requests launch
# two full pipeline runs in parallel.  On a typical 8 GB server, two
# concurrent Stage 3 UMAP + HDBSCAN runs will OOM or thrash disk.
# This module enforces a single-worker queue so pipeline runs execute
# one at a time regardless of how many upload requests arrive at once.
#
# Public API
# ----------
#   enqueue_run(job: dict) -> str
#       Adds a job to the queue and returns its run_id immediately
#       (non-blocking).  Raises QueueFullError if MAX_QUEUE_DEPTH is
#       already reached.
#
#   pipeline_worker()
#       Long-running async coroutine that pops jobs from the queue and
#       calls run_pipeline() sequentially.  Must be started as a
#       background task in the API's lifespan handler:
#
#           async with asyncio.TaskGroup() as tg:
#               tg.create_task(pipeline_worker())
#
#   current_queue_depth() -> int
#       Returns the number of jobs currently waiting (does not include
#       the job currently executing).
#
# Job dict schema
# ---------------
# A job is a plain dict with at least:
#   {
#       "run_id":        str,   # pre-generated by the API upload endpoint
#       "log_path":      str,   # absolute path to the uploaded log file
#       "embedding_model": any, # cached model object or None
#   }
#
# PLACEMENT: backend/queue.py
# ══════════════════════════════════════════════════════════════════════

from __future__ import annotations

import asyncio
import logging
import sys
from pathlib import Path
from typing import Any

# Allow imports from the project root (where config.py lives)
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import MAX_QUEUE_DEPTH, MAX_CONCURRENT_RUNS  # S1.2

logger = logging.getLogger("queue")


# ══════════════════════════════════════════════════════════════════════
# EXCEPTIONS
# ══════════════════════════════════════════════════════════════════════

class QueueFullError(RuntimeError):
    """
    Raised by enqueue_run() when the queue already holds MAX_QUEUE_DEPTH
    jobs.  The API upload endpoint should catch this and return HTTP 429.
    """
    pass


# ══════════════════════════════════════════════════════════════════════
# QUEUE STATE
# ══════════════════════════════════════════════════════════════════════

# asyncio.Queue with maxsize=0 means unbounded — we enforce the depth
# cap manually in enqueue_run() so we can raise QueueFullError with a
# clear message rather than blocking the caller.
_queue: asyncio.Queue[dict] = asyncio.Queue()

# Tracks how many jobs are currently waiting (not including the one
# actively executing).  Incremented in enqueue_run(), decremented when
# the worker picks the job up.
_pending_count: int = 0


# ══════════════════════════════════════════════════════════════════════
# PUBLIC API
# ══════════════════════════════════════════════════════════════════════

def enqueue_run(job: dict) -> str:
    """
    Add a pipeline job to the queue and return its run_id immediately.

    This function is synchronous and non-blocking — it does not await
    anything.  Call it from a regular (non-async) context or from inside
    an async function without await.

    Parameters
    ----------
    job : dict
        Must contain at minimum:
            "run_id"        : str   — pre-generated unique run identifier
            "log_path"      : str   — absolute path to the log file
            "embedding_model": any  — cached model or None

    Returns
    -------
    str — the run_id from the job dict (convenience, avoids a second
          dict lookup at the call site).

    Raises
    ------
    QueueFullError
        If the number of currently pending (waiting) jobs has already
        reached MAX_QUEUE_DEPTH.  The job that is currently executing
        does NOT count toward this limit.
    ValueError
        If job is missing the required "run_id" or "log_path" keys.
    """
    global _pending_count

    run_id   = job.get("run_id")
    log_path = job.get("log_path")

    if not run_id:
        raise ValueError("enqueue_run: job must contain a non-empty 'run_id'")
    if not log_path:
        raise ValueError("enqueue_run: job must contain a non-empty 'log_path'")

    if _pending_count >= MAX_QUEUE_DEPTH:
        raise QueueFullError(
            f"Pipeline queue is full ({_pending_count}/{MAX_QUEUE_DEPTH} jobs pending). "
            f"Please wait for a slot to become available.  "
            f"Increase MAX_QUEUE_DEPTH in config.py or via the MAX_QUEUE_DEPTH "
            f"environment variable to allow more concurrent queued jobs."
        )

    _pending_count += 1
    _queue.put_nowait(job)

    logger.info(
        "Job enqueued: run_id=%s  log=%s  queue_depth=%d/%d",
        run_id, Path(log_path).name, _pending_count, MAX_QUEUE_DEPTH,
    )

    return run_id


def current_queue_depth() -> int:
    """
    Return the number of jobs currently waiting in the queue.

    This does NOT include the job that is currently executing.  Use this
    for health-check endpoints or rate-limit decisions.
    """
    return _pending_count


# ══════════════════════════════════════════════════════════════════════
# BACKGROUND WORKER
# ══════════════════════════════════════════════════════════════════════

async def pipeline_worker() -> None:
    """
    Long-running async coroutine that processes pipeline jobs one at a
    time.

    Start this as a background task in the API's lifespan handler:

        asyncio.create_task(pipeline_worker())

    The worker runs forever (until the event loop shuts down).  Each
    job is executed by calling run_pipeline() via asyncio.to_thread()
    so the CPU-heavy pipeline stages do not block the event loop.

    If run_pipeline() raises an exception the error is logged and the
    worker continues processing the next job — a single bad run must
    not kill the server.

    MAX_CONCURRENT_RUNS is currently always 1 (enforced by the single
    worker pattern).  It is imported from config.py so that a future
    multi-worker upgrade only requires changing the config constant and
    spawning additional pipeline_worker() coroutines.
    """
    global _pending_count

    # Import here to avoid a circular import at module load time.
    # pipeline.py imports from config.py; queue.py also imports from
    # config.py — both are fine.  The circular risk is pipeline.py
    # importing queue.py which imports pipeline.py, which we avoid by
    # deferring the import to inside this coroutine.
    from pipeline import run_pipeline  # noqa: PLC0415

    logger.info(
        "Pipeline worker started — MAX_CONCURRENT_RUNS=%d, MAX_QUEUE_DEPTH=%d",
        MAX_CONCURRENT_RUNS, MAX_QUEUE_DEPTH,
    )

    while True:
        job: dict = await _queue.get()

        # Decrement pending count now that the worker has picked the job
        # up — it is no longer "waiting", it is "executing".
        _pending_count = max(0, _pending_count - 1)

        run_id   = job.get("run_id",        "unknown")
        log_path = job.get("log_path",       "")
        model    = job.get("embedding_model", None)

        logger.info(
            "Worker: starting run_id=%s  log=%s  queue_remaining=%d",
            run_id, Path(log_path).name if log_path else "?", _pending_count,
        )

        try:
            # Run the pipeline in a thread so the async event loop stays
            # responsive to incoming HTTP requests during the ~2-minute
            # Stage 3 execution.
            await asyncio.to_thread(
                run_pipeline,
                log_path        = log_path,
                run_id          = run_id,
                embedding_model = model,
            )
            logger.info("Worker: run_id=%s completed successfully", run_id)

        except Exception as exc:
            # run_pipeline() already writes "failed" status to run_info.json
            # and registers the failed run in the index before re-raising.
            # We catch here only to prevent the worker from dying.
            logger.error(
                "Worker: run_id=%s FAILED — %s",
                run_id, exc,
                exc_info=True,
            )

        finally:
            # Signal to asyncio that this task slot is free.
            _queue.task_done()